[pipeline]
input = dataset/DomesticDeclarations.xes.gz
output_dir = output
# Used only when conversion = false:
# knowledge_graph = output/previous_run/file.prov.ttl

conversion = true
visualization = false
validation = true

[validation]
R1 = true
R2 = true
R3 = true
