[pipeline]
;input = benchmarks\bench_r1_r2_r3_20260719_142519\DomesticDeclarations.corrupted.xes
output_dir = output
# Used only when conversion = false:
knowledge_graph = benchmarks/bench_r1_r2_r3_20260719_142519/DomesticDeclarations.corrupted.prov.ttl

conversion = false
visualization = false
validation = true

[validation]
R1 = true
R2 = true
R3 = true
