[pipeline]
;input = dataset/DomesticDeclarations.xes.gz
output_dir = output
# Used only when conversion = false:
knowledge_graph = benchmarks/bench_r1_r2_r3_r4_r5_r5b_r6_20260721_181212/DomesticDeclarations.corrupted.prov.ttl

conversion = false
visualization = false
validation = true

[validation]
R1 = true
R2 = true
R3 = true
R4 = true
R5 = true
R5B = true
R6 = true
