#!/usr/bin/env bash
# Start Apache Jena Fuseki and export SPARQL env vars for this shell.
#
# Usage:
#   source scripts/start_triplestore.sh
#   # or: . scripts/start_triplestore.sh

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE="$ROOT/docker-compose.fuseki.yml"

echo "==> Starting Fuseki (docker compose)..."
docker compose -f "$COMPOSE" up -d

echo "==> Waiting for Fuseki ping..."
deadline=$((SECONDS + 180))
ready=0
while (( SECONDS < deadline )); do
  if curl -sf "http://localhost:3030/\$/ping" >/dev/null; then
    ready=1
    break
  fi
  sleep 2
done
if [[ "$ready" -ne 1 ]]; then
  echo "Fuseki did not become ready within 3 minutes." >&2
  exit 1
fi
echo "==> Fuseki is ready."

export KG_SPARQL_QUERY_ENDPOINT="http://localhost:3030/ds/sparql"
export KG_SPARQL_UPDATE_ENDPOINT="http://localhost:3030/ds/update"
export KG_SPARQL_GSP_ENDPOINT="http://localhost:3030/ds/data"
export KG_SPARQL_USER="admin"
export KG_SPARQL_PASSWORD="admin"
export KG_SPARQL_TIMEOUT_SECONDS="${KG_SPARQL_TIMEOUT_SECONDS:-3600}"

cat > "$ROOT/scripts/triplestore.env.sh" <<'EOF'
# Auto-generated by start_triplestore.sh
export KG_SPARQL_QUERY_ENDPOINT="http://localhost:3030/ds/sparql"
export KG_SPARQL_UPDATE_ENDPOINT="http://localhost:3030/ds/update"
export KG_SPARQL_GSP_ENDPOINT="http://localhost:3030/ds/data"
export KG_SPARQL_USER="admin"
export KG_SPARQL_PASSWORD="admin"
export KG_SPARQL_TIMEOUT_SECONDS="${KG_SPARQL_TIMEOUT_SECONDS:-3600}"
EOF

echo
echo "SPARQL endpoints exported for this shell."
echo "Next: python scripts/run_triplestore_validation.py --ping"
echo "      python scripts/run_multi_run_experiment.py 10"
echo "Stop: source scripts/stop_triplestore.sh"
