# Start Apache Jena Fuseki and configure SPARQL env vars for this session.
#
# Usage (PowerShell) — dot-source so env vars apply to your shell:
#   . .\scripts\start_triplestore.ps1
#
# Then run experiments in the same shell:
#   python scripts\run_multi_run_experiment.py 10

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
if (-not $RepoRoot) { $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path }

$ComposeFile = Join-Path $RepoRoot "docker-compose.fuseki.yml"
$Query = "http://localhost:3030/ds/sparql"
$Update = "http://localhost:3030/ds/update"
$Gsp = "http://localhost:3030/ds/data"
$User = "admin"
$Password = "admin"

Write-Host "==> Starting Fuseki (docker compose)..." -ForegroundColor Cyan
Push-Location $RepoRoot
try {
    docker compose -f $ComposeFile up -d
} finally {
    Pop-Location
}

Write-Host "==> Waiting for Fuseki ping at http://localhost:3030/`$/ping ..." -ForegroundColor Cyan
$deadline = (Get-Date).AddMinutes(3)
$ready = $false
while ((Get-Date) -lt $deadline) {
    try {
        $resp = Invoke-WebRequest -Uri "http://localhost:3030/`$/ping" -UseBasicParsing -TimeoutSec 3
        if ($resp.StatusCode -eq 200) {
            $ready = $true
            break
        }
    } catch {
        Start-Sleep -Seconds 2
    }
}
if (-not $ready) {
    throw "Fuseki did not become ready within 3 minutes. Check: docker compose -f docker-compose.fuseki.yml logs"
}
Write-Host "==> Fuseki is ready." -ForegroundColor Green

$env:KG_SPARQL_QUERY_ENDPOINT = $Query
$env:KG_SPARQL_UPDATE_ENDPOINT = $Update
$env:KG_SPARQL_GSP_ENDPOINT = $Gsp
$env:KG_SPARQL_USER = $User
$env:KG_SPARQL_PASSWORD = $Password
if (-not $env:KG_SPARQL_TIMEOUT_SECONDS) {
    $env:KG_SPARQL_TIMEOUT_SECONDS = "3600"
}

$envFile = Join-Path $PSScriptRoot "triplestore.env.ps1"
@"
# Auto-generated by start_triplestore.ps1 — dot-source if needed:
#   . .\scripts\triplestore.env.ps1
`$env:KG_SPARQL_QUERY_ENDPOINT = '$Query'
`$env:KG_SPARQL_UPDATE_ENDPOINT = '$Update'
`$env:KG_SPARQL_GSP_ENDPOINT = '$Gsp'
`$env:KG_SPARQL_USER = '$User'
`$env:KG_SPARQL_PASSWORD = '$Password'
`$env:KG_SPARQL_TIMEOUT_SECONDS = '3600'
"@ | Set-Content -Path $envFile -Encoding UTF8

Write-Host ""
Write-Host "SPARQL endpoints configured for this session:" -ForegroundColor Green
Write-Host "  KG_SPARQL_QUERY_ENDPOINT  = $env:KG_SPARQL_QUERY_ENDPOINT"
Write-Host "  KG_SPARQL_UPDATE_ENDPOINT = $env:KG_SPARQL_UPDATE_ENDPOINT"
Write-Host "  KG_SPARQL_GSP_ENDPOINT    = $env:KG_SPARQL_GSP_ENDPOINT"
Write-Host "  Env file written: $envFile"
Write-Host ""
Write-Host "Next:" -ForegroundColor Cyan
Write-Host "  python scripts\run_triplestore_validation.py --ping"
Write-Host "  python scripts\run_multi_run_experiment.py 10"
Write-Host ""
Write-Host "Stop later with:  . .\scripts\stop_triplestore.ps1   (or .\scripts\stop_triplestore.ps1)"
